import express from 'express';
import { spawn } from 'child_process';
import { Client as FtpClient } from 'basic-ftp';
import { Readable } from 'stream';
import path from 'path';
import os from 'os';
import fs from 'fs';
import crypto from 'crypto';
import { fileURLToPath } from 'url';
import AdmZip from 'adm-zip';
import { getDatabase, saveDatabase, log } from '../db/sqlite.js';
import { uploadDirToSmb as smbUploadDir } from '../lib/smb.js';

const router = express.Router();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '../../..');
const mkpfsWorkDir = path.join(projectRoot, 'data', 'mkpfs');
const payloadsDir = path.join(projectRoot, 'data', 'payloads');

const MM_REPO = 'PSBrew/MicroMount';
const RELEASE_KEY = 'micromount_release_state';
const ASSET_REGEX = /\.(elf|lua|prx|sprx|bin|zip)$/i;

function ensureMkpfsDir() {
  if (!fs.existsSync(mkpfsWorkDir)) fs.mkdirSync(mkpfsWorkDir, { recursive: true });
}

function isInsideWorkDir(p) {
  const abs = path.resolve(p);
  const root = path.resolve(mkpfsWorkDir);
  return abs === root || abs.startsWith(root + path.sep);
}

const DEFAULT_CONFIG = {
  target_directory: '/data/homebrew',
  scan_paths: ['/data/homebrew'],
  scan_depth: 1,
  scan_interval_seconds: 30,
  debug: 1,
  lvd_image_type: 0,
  lvd_sector_size: 65536,
  lvd_secondary_unit: 65536,
  lvd_raw_flags: '0x9',
  pfs_fstype: 'pfs',
  pfs_mkeymode: 'AC',
  pfs_budgetid: 'system',
  pfs_sigverify: 0,
  pfs_playgo: 0,
  pfs_disc: 0,
  pfs_use_ekpfs: 1,
  pfs_read_only: 1,
  pfs_force: 0,
};

const CONFIG_KEY = 'micromount_config';
const FTP_KEY = 'micromount_ftp';
const BROWSER_PREFS_KEY = 'micromount_browser_prefs';

function loadBrowserPrefs() {
  const db = getDatabase();
  const stmt = db.prepare('SELECT value FROM settings WHERE key = ?');
  stmt.bind([BROWSER_PREFS_KEY]);
  let prefs = { local: '', smb: {} };
  if (stmt.step()) {
    try {
      const saved = JSON.parse(stmt.getAsObject().value);
      prefs = { local: saved.local || '', smb: saved.smb || {} };
    } catch (_) {}
  }
  stmt.free();
  return prefs;
}

function saveBrowserPrefs(prefs) {
  const db = getDatabase();
  const clean = { local: String(prefs.local || ''), smb: {} };
  if (prefs.smb && typeof prefs.smb === 'object') {
    for (const [k, v] of Object.entries(prefs.smb)) clean.smb[String(k)] = String(v || '');
  }
  db.run('INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)', [BROWSER_PREFS_KEY, JSON.stringify(clean)]);
  saveDatabase();
  return clean;
}

function loadConfig() {
  const db = getDatabase();
  const stmt = db.prepare('SELECT value FROM settings WHERE key = ?');
  stmt.bind([CONFIG_KEY]);
  let cfg = { ...DEFAULT_CONFIG };
  if (stmt.step()) {
    try {
      const saved = JSON.parse(stmt.getAsObject().value);
      cfg = { ...DEFAULT_CONFIG, ...saved };
    } catch (_) {}
  }
  stmt.free();
  return cfg;
}

function saveConfig(cfg) {
  const db = getDatabase();
  db.run('INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)', [CONFIG_KEY, JSON.stringify(cfg)]);
  saveDatabase();
}

function loadFtp() {
  const db = getDatabase();
  const stmt = db.prepare('SELECT value FROM settings WHERE key = ?');
  stmt.bind([FTP_KEY]);
  let ftp = { port: 2121, username: 'anonymous', password: '' };
  if (stmt.step()) {
    try {
      ftp = { ...ftp, ...JSON.parse(stmt.getAsObject().value) };
    } catch (_) {}
  }
  stmt.free();
  return ftp;
}

function saveFtp(ftp) {
  const db = getDatabase();
  db.run('INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)', [FTP_KEY, JSON.stringify(ftp)]);
  saveDatabase();
}

function buildConfigIni(cfg) {
  const lines = [];
  lines.push('# MicroMount runtime config');
  lines.push('# Generated by PS5WebPayload Manager');
  lines.push('# Place as: /data/micromount/config.ini');
  lines.push('');
  lines.push(`target_directory=${cfg.target_directory}`);
  lines.push(`debug=${cfg.debug ? 1 : 0}`);
  lines.push(`scan_depth=${cfg.scan_depth}`);
  lines.push(`scan_interval_seconds=${cfg.scan_interval_seconds}`);
  lines.push('');

  const localPaths = (cfg.scan_paths || []).filter(p => p && !/^smb:\/\//i.test(p));
  for (const p of localPaths) {
    lines.push(`scanpath=${p}`);
  }

  lines.push('');
  lines.push('# LVD mount profile');
  lines.push(`lvd_image_type=${cfg.lvd_image_type}`);
  lines.push(`lvd_sector_size=${cfg.lvd_sector_size}`);
  lines.push(`lvd_secondary_unit=${cfg.lvd_secondary_unit}`);
  lines.push(`lvd_raw_flags=${cfg.lvd_raw_flags}`);
  lines.push('');
  lines.push('# PFS mount profile');
  lines.push(`pfs_fstype=${cfg.pfs_fstype}`);
  lines.push(`pfs_mkeymode=${cfg.pfs_mkeymode}`);
  lines.push(`pfs_budgetid=${cfg.pfs_budgetid}`);
  lines.push(`pfs_sigverify=${cfg.pfs_sigverify}`);
  lines.push(`pfs_playgo=${cfg.pfs_playgo}`);
  lines.push(`pfs_disc=${cfg.pfs_disc}`);
  lines.push(`pfs_use_ekpfs=${cfg.pfs_use_ekpfs}`);
  lines.push(`pfs_read_only=${cfg.pfs_read_only}`);
  lines.push(`pfs_force=${cfg.pfs_force}`);
  lines.push('');
  return lines.join('\n');
}

router.get('/config', (req, res) => {
  try {
    res.json(loadConfig());
  } catch (err) {
    log('error', `MicroMount config get failed: ${err.message}`);
    res.status(500).json({ error: err.message });
  }
});

router.put('/config', (req, res) => {
  try {
    const cfg = { ...loadConfig(), ...req.body };
    if (!Array.isArray(cfg.scan_paths)) cfg.scan_paths = [];
    saveConfig(cfg);
    log('info', 'MicroMount config saved');
    res.json({ success: true, config: cfg });
  } catch (err) {
    log('error', `MicroMount config save failed: ${err.message}`);
    res.status(500).json({ error: err.message });
  }
});

router.get('/config-ini', (req, res) => {
  try {
    const ini = buildConfigIni(loadConfig());
    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.setHeader('Content-Disposition', 'attachment; filename="config.ini"');
    res.send(ini);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.get('/ftp', (req, res) => {
  const f = loadFtp();
  res.json({ ...f, password: f.password ? '__set__' : '' });
});

router.put('/ftp', (req, res) => {
  try {
    const cur = loadFtp();
    const next = {
      port: parseInt(req.body.port) || cur.port || 2121,
      username: req.body.username || cur.username || 'anonymous',
      password: req.body.password === '__set__' ? cur.password : (req.body.password ?? ''),
    };
    saveFtp(next);
    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

async function withFtp(ip, ftpOpts, fn) {
  const client = new FtpClient(15000);
  client.ftp.verbose = false;
  try {
    await client.access({
      host: ip,
      port: ftpOpts.port,
      user: ftpOpts.username || 'anonymous',
      password: ftpOpts.password || '',
      secure: false,
    });
    // Tune the control socket so a sleepy router / PS5 doesn't silently kill us.
    try { client.ftp.socket.setKeepAlive(true, 15_000); } catch (_) {}
    try { client.ftp.socket.setNoDelay(true); } catch (_) {}
    return await fn(client);
  } finally {
    try { client.close(); } catch (_) {}
  }
}

async function ensureRemoteDir(client, dir) {
  await client.ensureDir(dir);
}

// Periodically send a NOOP on a *separate* FTP control channel so the PS5
// homebrew FTP daemon (and any NAT in between) sees regular activity. The PS5
// can drop into rest mode after extended single-channel inactivity which kills
// long uploads — this keeps it visibly busy.
function startFtpHeartbeat(ip, ftpOpts, intervalMs = 25_000) {
  let stopped = false;
  let client = null;
  let busy = false;

  const tick = async () => {
    if (stopped || busy) return;
    busy = true;
    try {
      if (!client) {
        client = new FtpClient(8000);
        client.ftp.verbose = false;
        await client.access({
          host: ip,
          port: ftpOpts.port,
          user: ftpOpts.username || 'anonymous',
          password: ftpOpts.password || '',
          secure: false,
        });
        try { client.ftp.socket.setKeepAlive(true, 10_000); } catch (_) {}
      }
      await client.send('NOOP');
    } catch (_) {
      try { client?.close(); } catch (_) {}
      client = null;
    } finally {
      busy = false;
    }
  };

  const timer = setInterval(tick, intervalMs);
  setTimeout(tick, 5_000);

  return {
    stop: () => {
      if (stopped) return;
      stopped = true;
      clearInterval(timer);
      try { client?.close(); } catch (_) {}
      client = null;
    },
  };
}

// Resilient FTP upload with TCP keepalive, NOOP heartbeat, and automatic
// resume via APPE on connection drop. The PS5 FTP daemon often dies mid-stream
// when the console enters rest mode — without resume, the entire transfer is
// wasted; with this helper it picks up from the last successfully written byte
// after reconnect.
async function uploadFileResilient(ip, ftpOpts, localPath, destDir, remoteName, opts = {}) {
  const total = fs.statSync(localPath).size;
  const maxRetries = opts.maxRetries ?? 5;
  const onProgress = opts.onProgress || (() => {});
  const onLog = opts.onLog || (() => {});
  const enableHeartbeat = opts.heartbeat !== false;

  let attempt = 0;
  let lastError = null;

  while (attempt < maxRetries) {
    attempt++;
    const hb = enableHeartbeat ? startFtpHeartbeat(ip, ftpOpts) : null;
    try {
      await withFtp(ip, ftpOpts, async (client) => {
        await ensureRemoteDir(client, destDir);
        await client.cd(destDir);

        let startOffset = 0;
        if (attempt === 1) {
          // First attempt: enforce a clean overwrite.
          try { await client.remove(remoteName); } catch (_) {}
        } else {
          // Retry attempt: see how much already made it across.
          try {
            const sz = await client.size(remoteName);
            if (sz >= total) {
              // Looks complete (or oversize from a corrupt prior run) — restart.
              try { await client.remove(remoteName); } catch (_) {}
              startOffset = 0;
            } else if (sz > 0) {
              startOffset = sz;
            }
          } catch (_) { startOffset = 0; }
        }

        if (startOffset > 0) {
          onLog(`[manager] Resuming at ${startOffset}/${total} bytes (attempt ${attempt})\n`);
          onProgress({ bytes: startOffset, total });
          const stream = fs.createReadStream(localPath, { start: startOffset });
          let bytes = startOffset;
          stream.on('data', (chunk) => {
            bytes += chunk.length;
            onProgress({ bytes, total });
          });
          await client.appendFrom(stream, remoteName);
        } else {
          if (attempt > 1) onLog(`[manager] Restarting upload from 0 (attempt ${attempt})\n`);
          client.trackProgress((info) => {
            if (info && typeof info.bytes === 'number') onProgress({ bytes: info.bytes, total });
          });
          try {
            await client.uploadFrom(localPath, remoteName);
          } finally {
            client.trackProgress();
          }
        }
      });
      onProgress({ bytes: total, total });
      return;
    } catch (e) {
      lastError = e;
      onLog(`[manager] WARN: attempt ${attempt} failed: ${e.message}\n`);
      if (attempt >= maxRetries) break;
      const wait = Math.min(15_000, 2_000 * attempt);
      onLog(`[manager] Waiting ${Math.round(wait / 1000)}s then retrying...\n`);
      await new Promise((r) => setTimeout(r, wait));
    } finally {
      if (hb) hb.stop();
    }
  }
  throw lastError || new Error('Upload failed');
}

router.post('/push-config', async (req, res) => {
  try {
    const { ip } = req.body;
    if (!ip) return res.status(400).json({ error: 'IP required' });
    const ftp = loadFtp();
    const ini = buildConfigIni(loadConfig());

    await withFtp(ip, ftp, async (client) => {
      await ensureRemoteDir(client, '/data/micromount');
      await client.cd('/data/micromount');
      const stream = Readable.from([Buffer.from(ini, 'utf8')]);
      await client.uploadFrom(stream, 'config.ini');
    });

    log('info', `MicroMount config pushed to ${ip}:${ftp.port}`);
    res.json({ success: true, message: `config.ini uploaded to ${ip}:/data/micromount/config.ini` });
  } catch (err) {
    log('error', `MicroMount push-config failed: ${err.message}`);
    res.status(500).json({ error: err.message });
  }
});

router.post('/test-ftp', async (req, res) => {
  try {
    const { ip } = req.body;
    if (!ip) return res.status(400).json({ error: 'IP required' });
    const ftp = loadFtp();
    const list = await withFtp(ip, ftp, async (client) => {
      return await client.list('/data');
    });
    res.json({ success: true, count: list.length });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.post('/ftp/browse', async (req, res) => {
  try {
    const { ip, path: reqPath = '/' } = req.body || {};
    if (!ip) return res.status(400).json({ error: 'IP required' });
    const cleaned = (reqPath || '/').replace(/\/+/g, '/');
    const target = cleaned.startsWith('/') ? cleaned : `/${cleaned}`;
    const ftp = loadFtp();
    const list = await withFtp(ip, ftp, async (client) => {
      try { await client.cd(target); }
      catch (e) { throw new Error(`cd ${target}: ${e.message}`); }
      return await client.list();
    });
    const files = list
      .filter(f => f.name !== '.' && f.name !== '..')
      .map(f => ({
        name: f.name,
        isDir: f.type === 2 || f.isDirectory === true,
        size: typeof f.size === 'number' ? f.size : 0,
        mtime: f.modifiedAt ? new Date(f.modifiedAt).getTime() : 0,
      }));
    files.sort((a, b) => Number(b.isDir) - Number(a.isDir) || a.name.localeCompare(b.name));
    const tNoTrail = target === '/' ? '/' : target.replace(/\/+$/, '');
    const parent = tNoTrail === '/' ? null : (tNoTrail.split('/').slice(0, -1).join('/') || '/');
    res.json({ success: true, path: tNoTrail, parent, files });
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

router.post('/ftp/delete', async (req, res) => {
  try {
    const { ip, path: target, isDir } = req.body || {};
    if (!ip || !target) return res.status(400).json({ error: 'ip and path required' });
    const ftp = loadFtp();
    await withFtp(ip, ftp, async (client) => {
      if (isDir) {
        await client.removeDir(target);
      } else {
        await client.remove(target);
      }
    });
    log('info', `FTP delete ${ip}:${target}${isDir ? ' (dir)' : ''}`);
    res.json({ success: true });
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

router.post('/ftp/upload', async (req, res) => {
  try {
    const { ip, dest_path = '/data', local_path } = req.body || {};
    if (!ip || !local_path) return res.status(400).json({ error: 'ip and local_path required' });
    const ftp = loadFtp();
    const absPath = path.resolve(local_path);
    if (!isLocalPathAllowed(absPath)) return res.status(403).json({ error: 'Path not allowed' });
    if (!fs.existsSync(absPath) || !fs.statSync(absPath).isFile()) return res.status(400).json({ error: 'Source file not found' });

    await uploadFileResilient(ip, ftp, absPath, dest_path, path.basename(absPath), {
      onLog: (line) => log('info', line.trim()),
    });
    log('info', `FTP upload ${absPath} -> ${ip}:${dest_path}`);
    res.json({ success: true, message: `Uploaded to ${dest_path}` });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.post('/local/delete', (req, res) => {
  try {
    const { path: target, isDir } = req.body || {};
    if (!target) return res.status(400).json({ error: 'path required' });
    const abs = path.resolve(target);
    if (!isLocalPathAllowed(abs)) return res.status(403).json({ error: `Path not allowed: ${abs}` });
    if (!fs.existsSync(abs)) return res.status(404).json({ error: 'Path not found' });
    const st = fs.statSync(abs);
    if (st.isDirectory() && !isDir) return res.status(400).json({ error: 'Path is a directory; pass isDir=true' });
    if (!st.isDirectory() && isDir) return res.status(400).json({ error: 'Path is a file; do not pass isDir=true' });
    fs.rmSync(abs, { recursive: !!isDir, force: true });
    log('info', `local delete ${abs}${isDir ? ' (dir)' : ''}`);
    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.post('/sources/:id/delete', async (req, res) => {
  try {
    const id = parseInt(req.params.id);
    const src = getSource(id);
    if (!src) return res.status(404).json({ error: 'Source not found' });
    if (src.type !== 'smb') return res.status(400).json({ error: 'Only SMB sources support delete' });
    const { path: target, isDir } = req.body || {};
    if (!target) return res.status(400).json({ error: 'path required' });

    const clean = target.replace(/\\/g, '/').replace(/^\/+/, '').replace(/\/+$/, '');
    if (!clean) return res.status(400).json({ error: 'Refusing to delete share root' });

    const args = buildSmbArgs(src);
    const dir = clean.includes('/') ? clean.replace(/\/[^/]+$/, '') : '';
    const name = clean.includes('/') ? clean.replace(/^.*\//, '') : clean;
    const cmds = [];
    if (dir) cmds.push(`cd "${dir}"`);
    if (isDir) {
      cmds.push(`deltree "${name}"`);
    } else {
      cmds.push(`del "${name}"`);
    }
    args.push('-c', cmds.join('; '));

    const { stdout, stderr, code } = await runSmbClient(args);
    const combined = (stdout || '') + '\n' + (stderr || '');
    const err = smbClientError(combined, code);
    if (err) return res.status(400).json({ error: err.message, smb_status: err.status });
    log('info', `SMB delete //${src.smb_host}/${src.smb_share}/${clean}${isDir ? ' (dir)' : ''}`);
    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.get('/sources', (req, res) => {
  try {
    const db = getDatabase();
    const rows = [];
    const stmt = db.prepare('SELECT * FROM micromount_sources ORDER BY created_at DESC');
    while (stmt.step()) rows.push(stmt.getAsObject());
    stmt.free();
    rows.forEach(r => { if (r.smb_password) r.smb_password = '__set__'; });
    res.json(rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.post('/sources', (req, res) => {
  try {
    const { name, type, path: srcPath, smb_host, smb_share, smb_username, smb_password, smb_domain } = req.body;
    if (!name || !type) return res.status(400).json({ error: 'name and type required' });
    if (type !== 'local' && type !== 'smb') return res.status(400).json({ error: 'type must be local or smb' });
    if (type === 'smb' && (!smb_host || !smb_share)) {
      return res.status(400).json({ error: 'smb_host and smb_share required for smb type' });
    }

    const db = getDatabase();
    db.run(
      `INSERT INTO micromount_sources (name, type, path, smb_host, smb_share, smb_username, smb_password, smb_domain)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
      [name, type, srcPath || '', smb_host || null, smb_share || null, smb_username || null, smb_password || null, smb_domain || null]
    );
    saveDatabase();
    const id = db.exec('SELECT last_insert_rowid()')[0].values[0][0];
    log('info', `MicroMount source added: ${name} (${type})`);
    res.json({ success: true, id });
  } catch (err) {
    log('error', `MicroMount source add failed: ${err.message}`);
    res.status(500).json({ error: err.message });
  }
});

router.put('/sources/:id', (req, res) => {
  try {
    const id = parseInt(req.params.id);
    const db = getDatabase();
    const cur = db.prepare('SELECT * FROM micromount_sources WHERE id = ?');
    cur.bind([id]);
    if (!cur.step()) {
      cur.free();
      return res.status(404).json({ error: 'Not found' });
    }
    const existing = cur.getAsObject();
    cur.free();

    const next = { ...existing, ...req.body };
    if (req.body.smb_password === '__set__') next.smb_password = existing.smb_password;
    if (typeof next.enabled === 'boolean') next.enabled = next.enabled ? 1 : 0;

    db.run(
      `UPDATE micromount_sources SET name=?, type=?, path=?, smb_host=?, smb_share=?, smb_username=?, smb_password=?, smb_domain=?, enabled=?, updated_at=CURRENT_TIMESTAMP WHERE id=?`,
      [next.name, next.type, next.path, next.smb_host, next.smb_share, next.smb_username, next.smb_password, next.smb_domain, next.enabled ? 1 : 0, id]
    );
    saveDatabase();
    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.delete('/sources/:id', (req, res) => {
  try {
    const id = parseInt(req.params.id);
    const db = getDatabase();
    db.run('DELETE FROM micromount_sources WHERE id = ?', [id]);
    saveDatabase();
    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

function getSource(id) {
  const db = getDatabase();
  const stmt = db.prepare('SELECT * FROM micromount_sources WHERE id = ?');
  stmt.bind([id]);
  let row = null;
  if (stmt.step()) row = stmt.getAsObject();
  stmt.free();
  return row;
}

function runSmbClient(args, input) {
  return new Promise((resolve, reject) => {
    const proc = spawn('smbclient', args);
    let stdout = '';
    let stderr = '';
    proc.stdout.on('data', d => { stdout += d.toString(); });
    proc.stderr.on('data', d => { stderr += d.toString(); });
    proc.on('error', reject);
    proc.on('close', (code) => {
      resolve({ stdout, stderr, code });
    });
    if (input) {
      proc.stdin.write(input);
      proc.stdin.end();
    }
  });
}

function smbClientError(out, code) {
  const m = out.match(/(NT_STATUS_(?!OK\b)[A-Z_]+)/);
  if (m) {
    const status = m[1];
    const msg = status === 'NT_STATUS_OBJECT_NAME_NOT_FOUND' ? 'Path not found'
      : status === 'NT_STATUS_ACCESS_DENIED' ? 'Access denied'
      : status === 'NT_STATUS_LOGON_FAILURE' ? 'Authentication failed (check username/password)'
      : status === 'NT_STATUS_BAD_NETWORK_NAME' ? 'Share not found'
      : status === 'NT_STATUS_HOST_UNREACHABLE' || status === 'NT_STATUS_CONNECTION_REFUSED' ? 'Host unreachable'
      : status === 'NT_STATUS_NO_SUCH_FILE' ? 'No matching files'
      : status;
    return { status, message: msg };
  }
  if (code !== 0) return { status: 'EXIT', message: out.trim().split('\n').slice(-3).join(' ') || `smbclient exit ${code}` };
  return null;
}

function buildSmbArgs(src) {
  const target = `//${src.smb_host}/${src.smb_share}`;
  const args = [target];
  if (src.smb_password) args.push(src.smb_password);
  if (src.smb_username) args.push('-U', src.smb_domain ? `${src.smb_domain}\\${src.smb_username}` : src.smb_username);
  else args.push('-N');
  return args;
}

function parseSmbList(output) {
  const files = [];
  const lines = output.split('\n');
  for (const line of lines) {
    const m = line.match(/^\s{2}(.+?)\s{2,}([DAHRSN]*)\s+(\d+)\s+(.+)$/);
    if (m) {
      const name = m[1].trim();
      const attrs = m[2];
      const size = parseInt(m[3]);
      if (name === '.' || name === '..') continue;
      files.push({
        name,
        size,
        isDir: attrs.includes('D'),
      });
    }
  }
  return files;
}

router.post('/sources/:id/browse', async (req, res) => {
  try {
    const id = parseInt(req.params.id);
    const src = getSource(id);
    if (!src) return res.status(404).json({ error: 'Source not found' });

    if (src.type === 'local') {
      return res.json({ success: true, type: 'local', path: src.path, files: [], message: 'Local PS5 path - browsed by MicroMount on PS5' });
    }

    let subPath = req.body && req.body.subPath;
    if (subPath === undefined || subPath === null) subPath = src.path || '';
    const cleanPath = subPath.replace(/\\/g, '/').replace(/^\/+/, '').replace(/\/+$/, '');
    const cmd = cleanPath ? `cd "${cleanPath}"; ls` : 'ls';

    const args = buildSmbArgs(src);
    args.push('-c', cmd);

    const { stdout, stderr, code } = await runSmbClient(args);
    const combined = (stdout || '') + '\n' + (stderr || '');
    const err = smbClientError(combined, code);
    if (err) {
      return res.status(400).json({ error: `${err.message}: ${cleanPath || '/'}`, smb_status: err.status });
    }

    const files = parseSmbList(stdout);
    res.json({ success: true, type: 'smb', path: cleanPath, files });
  } catch (err) {
    log('error', `MicroMount browse failed: ${err.message}`);
    res.status(500).json({ error: err.message });
  }
});

router.post('/sources/:id/sync', async (req, res) => {
  try {
    const id = parseInt(req.params.id);
    const src = getSource(id);
    if (!src) return res.status(404).json({ error: 'Source not found' });
    if (src.type !== 'smb') return res.status(400).json({ error: 'Sync only available for smb sources' });

    const { ip, dest_path = '/data/homebrew', subPath = '' } = req.body;
    if (!ip) return res.status(400).json({ error: 'PS5 IP required' });

    const ftp = loadFtp();
    const sharePath = subPath || src.path || '';
    const cleanShare = sharePath.replace(/\\/g, '/').replace(/^\/+/, '');

    const lsArgs = buildSmbArgs(src);
    lsArgs.push('-c', cleanShare ? `cd "${cleanShare}"; ls` : 'ls');
    const { stdout, code: lsCode } = await runSmbClient(lsArgs);
    const lsErr = smbClientError(stdout, lsCode);
    if (lsErr) return res.status(400).json({ error: `${lsErr.message}: ${cleanShare || '/'}`, smb_status: lsErr.status });
    const files = parseSmbList(stdout).filter(f => !f.isDir && /\.ffpfsc$/i.test(f.name));

    if (files.length === 0) {
      return res.json({ success: true, synced: [], message: 'No .ffpfsc files found' });
    }

    const tmpDir = fs.mkdtempSync(path.join(getDiskTmpRoot(), 'mm-sync-'));
    const synced = [];
    const failed = [];

    try {
      for (const f of files) {
        const localPath = path.join(tmpDir, f.name);
        const getArgs = buildSmbArgs(src);
        const remote = cleanShare ? `${cleanShare}/${f.name}` : f.name;
        getArgs.push('-c', `get "${remote}" "${localPath}"`);
        try {
          const { stdout: getOut, code: getCode } = await runSmbClient(getArgs);
          const getErr = smbClientError(getOut, getCode);
          if (getErr) throw new Error(getErr.message);
        } catch (e) {
          failed.push({ name: f.name, error: e.message });
          continue;
        }

        try {
          await withFtp(ip, ftp, async (client) => {
            await ensureRemoteDir(client, dest_path);
            await client.cd(dest_path);
            await client.uploadFrom(localPath, f.name);
          });
          synced.push({ name: f.name, size: f.size });
        } catch (e) {
          failed.push({ name: f.name, error: e.message });
        }

        try { fs.unlinkSync(localPath); } catch (_) {}
      }
    } finally {
      try { fs.rmdirSync(tmpDir); } catch (_) {}
    }

    log('info', `MicroMount sync ${src.name} -> ${ip}: ${synced.length} ok, ${failed.length} failed`);
    res.json({ success: true, synced, failed, dest_path });
  } catch (err) {
    log('error', `MicroMount sync failed: ${err.message}`);
    res.status(500).json({ error: err.message });
  }
});

router.post('/sources/:id/test', async (req, res) => {
  try {
    const id = parseInt(req.params.id);
    const src = getSource(id);
    if (!src) return res.status(404).json({ error: 'Source not found' });
    if (src.type !== 'smb') return res.json({ success: true, type: 'local' });

    const args = buildSmbArgs(src);
    args.push('-c', 'ls');
    const { stdout, code } = await runSmbClient(args);
    const e = smbClientError(stdout, code);
    if (e) return res.status(400).json({ error: e.message, smb_status: e.status });
    res.json({ success: true, message: 'SMB connection OK' });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

const MKPFS_BIN = process.env.MKPFS_BIN || 'mkpfs';
const MAX_LOG_LINES = 2000;
const jobs = new Map();

function newJobId() { return crypto.randomBytes(8).toString('hex'); }

function appendLog(job, chunk) {
  const text = chunk.toString();
  job.log += text;
  const lines = job.log.split('\n');
  if (lines.length > MAX_LOG_LINES) {
    job.log = lines.slice(-MAX_LOG_LINES).join('\n');
  }
  updateProgressFromText(job, text);
}

function updateProgressFromText(job, text) {
  if (!text) return;
  // grab the last percentage figure seen in the chunk (works for 7z -bsp1, unrar, mkpfs --verbose)
  const matches = text.match(/(\d{1,3})\s*%/g);
  if (matches && matches.length) {
    const last = matches[matches.length - 1];
    const n = parseInt(last);
    if (!isNaN(n) && n >= 0 && n <= 100) {
      job.progress = n;
    }
    return;
  }
  // fallback: "X / Y" style counters (mkpfs blocks etc.)
  const ratio = text.match(/(\d+)\s*\/\s*(\d+)/);
  if (ratio) {
    const a = parseInt(ratio[1]);
    const b = parseInt(ratio[2]);
    if (b > 0 && a >= 0 && a <= b) {
      job.progress = Math.round((a / b) * 100);
    }
  }
}

function listMkpfsFiles(dir, base = '') {
  const entries = [];
  if (!fs.existsSync(dir)) return entries;
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name);
    let stat;
    try { stat = fs.statSync(full); } catch (_) { continue; }
    const rel = path.posix.join(base, name);
    if (stat.isDirectory()) {
      entries.push({ name, path: rel, isDir: true });
    } else {
      entries.push({ name, path: rel, isDir: false, size: stat.size, mtime: stat.mtimeMs });
    }
  }
  return entries.sort((a, b) => Number(b.isDir) - Number(a.isDir) || a.name.localeCompare(b.name));
}

router.get('/mkpfs/status', async (req, res) => {
  const proc = spawn(MKPFS_BIN, ['--help']);
  let output = '';
  proc.stdout.on('data', d => { output += d.toString(); });
  proc.stderr.on('data', d => { output += d.toString(); });
  proc.on('error', () => {
    res.json({ installed: false, workdir: mkpfsWorkDir });
  });
  proc.on('close', (code) => {
    if (code === 0) {
      res.json({
        installed: true,
        bin: MKPFS_BIN,
        workdir: mkpfsWorkDir,
        help_excerpt: output.split('\n').slice(0, 4).join('\n'),
      });
    } else {
      res.json({ installed: false, workdir: mkpfsWorkDir, error: output.trim() });
    }
  });
});

const BLOCKED_LOCAL_PREFIXES = [
  '/etc', '/root', '/sys', '/proc', '/boot', '/usr', '/bin', '/sbin',
  '/lib', '/lib32', '/lib64', '/dev', '/run', '/var/run', '/var/cache',
  '/var/lib/docker', '/var/lib/containers', '/var/lib/snapd', '/snap',
];

function isLocalPathAllowed(absPath) {
  const norm = path.resolve(absPath);
  for (const prefix of BLOCKED_LOCAL_PREFIXES) {
    if (norm === prefix || norm.startsWith(prefix + path.sep)) return false;
  }
  return true;
}

router.post('/local/browse', (req, res) => {
  try {
    const { path: reqPath = '/mnt' } = req.body || {};
    const target = path.resolve(reqPath || '/mnt');
    if (!isLocalPathAllowed(target)) {
      return res.status(403).json({ error: `Path not allowed: ${target}` });
    }
    if (!fs.existsSync(target)) return res.status(404).json({ error: 'Path not found' });
    const stat = fs.statSync(target);
    if (!stat.isDirectory()) return res.status(400).json({ error: 'Not a directory' });

    const files = [];
    let entries;
    try { entries = fs.readdirSync(target, { withFileTypes: true }); }
    catch (e) { return res.status(403).json({ error: `Cannot read: ${e.message}` }); }

    for (const e of entries) {
      const full = path.join(target, e.name);
      let s;
      try { s = fs.statSync(full); } catch (_) { continue; }
      files.push({
        name: e.name,
        isDir: e.isDirectory() || s.isDirectory(),
        size: s.size,
        mtime: s.mtimeMs,
      });
    }
    files.sort((a, b) => Number(b.isDir) - Number(a.isDir) || a.name.localeCompare(b.name));

    const parent = path.dirname(target);
    res.json({
      success: true,
      path: target,
      parent: target === '/' ? null : parent,
      files,
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

function loadReleaseState() {
  const db = getDatabase();
  const stmt = db.prepare('SELECT value FROM settings WHERE key = ?');
  stmt.bind([RELEASE_KEY]);
  let s = { version: null, published_at: null, checked_at: null, last_update_at: null, assets: [] };
  if (stmt.step()) {
    try { s = { ...s, ...JSON.parse(stmt.getAsObject().value) }; } catch (_) {}
  }
  stmt.free();
  return s;
}

function saveReleaseState(s) {
  const db = getDatabase();
  db.run('INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)', [RELEASE_KEY, JSON.stringify(s)]);
  saveDatabase();
}

async function fetchLatestRelease() {
  const url = `https://api.github.com/repos/${MM_REPO}/releases/latest`;
  const r = await fetch(url, {
    headers: {
      'Accept': 'application/vnd.github.v3+json',
      'User-Agent': 'ps5webpayload-manager',
    },
  });
  if (!r.ok) throw new Error(`GitHub API ${r.status}`);
  return r.json();
}

function ensurePayloadsDir() {
  if (!fs.existsSync(payloadsDir)) fs.mkdirSync(payloadsDir, { recursive: true });
}

async function downloadAssetBuffer(url) {
  const r = await fetch(url, {
    redirect: 'follow',
    headers: { 'User-Agent': 'ps5webpayload-manager' },
  });
  if (!r.ok) throw new Error(`download ${url}: HTTP ${r.status}`);
  return Buffer.from(await r.arrayBuffer());
}

const PAYLOAD_EXT_REGEX = /\.(elf|lua|prx|sprx|bin)$/i;

function upsertPayloadRow(name, filepath, sourceUrl, size, version) {
  const db = getDatabase();
  const findStmt = db.prepare('SELECT id FROM payloads WHERE name = ? OR filename = ?');
  findStmt.bind([name, name]);
  const exists = findStmt.step();
  const id = exists ? findStmt.getAsObject().id : null;
  findStmt.free();
  if (id != null) {
    db.run(
      'UPDATE payloads SET filename = ?, filepath = ?, source_url = ?, size = ?, version = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?',
      [name, filepath, sourceUrl, size, version, id],
    );
  } else {
    db.run(
      'INSERT INTO payloads (name, filename, filepath, source_url, size, version) VALUES (?, ?, ?, ?, ?, ?)',
      [name, name, filepath, sourceUrl, size, version],
    );
  }
  saveDatabase();
}

async function downloadReleaseAssets(release) {
  ensurePayloadsDir();
  const version = release.tag_name || release.name || 'latest';
  const downloaded = [];
  for (const asset of (release.assets || [])) {
    if (!ASSET_REGEX.test(asset.name)) continue;
    const buf = await downloadAssetBuffer(asset.browser_download_url);

    if (/\.zip$/i.test(asset.name)) {
      try {
        const zip = new AdmZip(buf);
        for (const entry of zip.getEntries()) {
          if (entry.isDirectory) continue;
          if (!PAYLOAD_EXT_REGEX.test(entry.entryName)) continue;
          const entryBuf = entry.getData();
          const filename = entry.entryName.split('/').pop();
          const filepath = path.join(payloadsDir, filename);
          fs.writeFileSync(filepath, entryBuf);
          upsertPayloadRow(filename, filepath, asset.browser_download_url, entryBuf.length, version);
          downloaded.push({ name: filename, size: entryBuf.length, version, from_zip: asset.name });
          log('info', `MicroMount release ${version}: extracted ${filename} from ${asset.name} (${entryBuf.length} bytes)`);
        }
      } catch (e) {
        log('error', `MicroMount: failed to extract ${asset.name}: ${e.message}`);
      }
    } else {
      const filepath = path.join(payloadsDir, asset.name);
      fs.writeFileSync(filepath, buf);
      upsertPayloadRow(asset.name, filepath, asset.browser_download_url, buf.length, version);
      downloaded.push({ name: asset.name, size: buf.length, version });
      log('info', `MicroMount release ${version}: downloaded ${asset.name} (${buf.length} bytes)`);
    }
  }
  return { version, published_at: release.published_at, downloaded };
}

async function checkRelease({ autoDownload = false } = {}) {
  const release = await fetchLatestRelease();
  const latestVersion = release.tag_name || release.name || 'latest';
  const state = loadReleaseState();
  const updateAvailable = !state.version || state.version !== latestVersion;
  const result = {
    current_version: state.version,
    latest_version: latestVersion,
    latest_published_at: release.published_at,
    update_available: updateAvailable,
    assets: (release.assets || []).filter(a => ASSET_REGEX.test(a.name)).map(a => ({ name: a.name, size: a.size })),
    downloaded: null,
  };
  state.checked_at = new Date().toISOString();
  if (updateAvailable && autoDownload) {
    const dl = await downloadReleaseAssets(release);
    state.version = dl.version;
    state.published_at = dl.published_at;
    state.last_update_at = new Date().toISOString();
    state.assets = dl.downloaded.map(d => d.name);
    result.downloaded = dl;
    result.current_version = state.version;
    result.update_available = false;
  }
  saveReleaseState(state);
  return result;
}

router.get('/release/status', (req, res) => {
  try {
    res.json(loadReleaseState());
  } catch (e) { res.status(500).json({ error: e.message }); }
});

router.post('/release/check', async (req, res) => {
  try {
    const result = await checkRelease({ autoDownload: false });
    res.json(result);
  } catch (e) {
    res.status(502).json({ error: e.message });
  }
});

router.post('/release/update', async (req, res) => {
  try {
    const result = await checkRelease({ autoDownload: true });
    res.json(result);
  } catch (e) {
    res.status(502).json({ error: e.message });
  }
});

router.get('/browser-prefs', (req, res) => {
  try { res.json(loadBrowserPrefs()); }
  catch (e) { res.status(500).json({ error: e.message }); }
});

router.put('/browser-prefs', (req, res) => {
  try {
    const cur = loadBrowserPrefs();
    const next = { ...cur, ...(req.body || {}) };
    if (req.body && typeof req.body.smb === 'object') next.smb = { ...cur.smb, ...req.body.smb };
    res.json(saveBrowserPrefs(next));
  } catch (e) { res.status(500).json({ error: e.message }); }
});

router.get('/local/roots', (req, res) => {
  const roots = [];
  for (const r of ['/mnt', '/home', '/data', '/tmp', '/media', '/srv']) {
    try {
      if (fs.existsSync(r) && fs.statSync(r).isDirectory()) roots.push(r);
    } catch (_) {}
  }
  roots.push(mkpfsWorkDir);
  res.json({ roots: [...new Set(roots)] });
});

router.post('/local/import-file', (req, res) => {
  try {
    const { path: srcPath, dest_name } = req.body || {};
    if (!srcPath) return res.status(400).json({ error: 'path required' });
    const src = path.resolve(srcPath);
    if (!isLocalPathAllowed(src)) return res.status(403).json({ error: 'Path not allowed' });
    if (!fs.existsSync(src) || !fs.statSync(src).isFile()) return res.status(400).json({ error: 'Source must be a file' });

    ensureMkpfsDir();
    const name = (dest_name || path.basename(src)).replace(/[^A-Za-z0-9_.\-]/g, '_');
    const dst = path.join(mkpfsWorkDir, name);
    fs.copyFileSync(src, dst);
    const stat = fs.statSync(dst);
    log('info', `local import file: ${src} -> ${dst} (${stat.size} bytes)`);
    res.json({ success: true, file: name, size: stat.size, dest: dst });
  } catch (err) {
    log('error', `local import file failed: ${err.message}`);
    res.status(500).json({ error: err.message });
  }
});

router.post('/local/import-folder', async (req, res) => {
  try {
    const { path: srcPath, dest_name } = req.body || {};
    if (!srcPath) return res.status(400).json({ error: 'path required' });
    const src = path.resolve(srcPath);
    if (!isLocalPathAllowed(src)) return res.status(403).json({ error: 'Path not allowed' });
    if (!fs.existsSync(src) || !fs.statSync(src).isDirectory()) return res.status(400).json({ error: 'Source must be a directory' });

    ensureMkpfsDir();
    const name = (dest_name || path.basename(src)).replace(/[^A-Za-z0-9_.\-]/g, '_');
    const dst = path.join(mkpfsWorkDir, name);
    if (!fs.existsSync(dst)) fs.mkdirSync(dst, { recursive: true });

    const jobId = newJobId();
    const job = {
      id: jobId,
      type: 'local-folder-import',
      status: 'running',
      log: '',
      started_at: new Date().toISOString(),
      finished_at: null,
      src, dst,
      error: null,
    };
    folderImportJobs.set(jobId, job);
    res.json({ success: true, job_id: jobId, dest: dst });

    appendLog(job, `[manager] rsync ${src}/ -> ${dst}/\n`);
    spawnIntoJob(job, 'rsync', ['-rt', '--info=progress2', `${src.replace(/\/?$/, '/')}`, `${dst.replace(/\/?$/, '/')}`])
      .then(r => {
        job.exit_code = r.code;
        job.finished_at = new Date().toISOString();
        if (r.code === 0) job.status = 'completed';
        else { job.status = 'failed'; job.error = r.error || `exit ${r.code}`; }
        log('info', `local folder import ${jobId} ${job.status}`);
      });
  } catch (err) {
    log('error', `local folder import failed: ${err.message}`);
    res.status(500).json({ error: err.message });
  }
});

router.get('/mkpfs/files', (req, res) => {
  try {
    ensureMkpfsDir();
    const sub = (req.query.sub || '').toString().replace(/\\/g, '/').replace(/^\/+/, '');
    const dir = path.resolve(mkpfsWorkDir, sub);
    if (!isInsideWorkDir(dir)) return res.status(400).json({ error: 'Out of work dir' });
    if (!fs.existsSync(dir)) return res.json({ workdir: mkpfsWorkDir, sub, files: [] });
    res.json({ workdir: mkpfsWorkDir, sub, files: listMkpfsFiles(dir, sub) });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.delete('/mkpfs/files', (req, res) => {
  try {
    const sub = (req.query.sub || '').toString().replace(/\\/g, '/').replace(/^\/+/, '');
    if (!sub) return res.status(400).json({ error: 'sub required' });
    const target = path.resolve(mkpfsWorkDir, sub);
    if (!isInsideWorkDir(target)) return res.status(400).json({ error: 'Out of work dir' });
    if (!fs.existsSync(target)) return res.json({ success: true });
    const stat = fs.statSync(target);
    if (stat.isDirectory()) fs.rmSync(target, { recursive: true, force: true });
    else fs.unlinkSync(target);
    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.post('/mkpfs/import-from-smb', async (req, res) => {
  try {
    const { source_id, smb_path, filename } = req.body;
    if (!source_id || !filename) return res.status(400).json({ error: 'source_id and filename required' });
    const src = getSource(parseInt(source_id));
    if (!src || src.type !== 'smb') return res.status(404).json({ error: 'SMB source not found' });

    ensureMkpfsDir();
    const cleanShare = (smb_path || src.path || '').replace(/\\/g, '/').replace(/^\/+/, '');
    const remote = cleanShare ? `${cleanShare}/${filename}` : filename;
    const localPath = path.join(mkpfsWorkDir, filename);

    const args = buildSmbArgs(src);
    args.push('-c', `get "${remote}" "${localPath}"`);
    const { stdout, code } = await runSmbClient(args);
    const err = smbClientError(stdout, code);
    if (err) return res.status(400).json({ error: err.message, smb_status: err.status });

    const stat = fs.statSync(localPath);
    log('info', `mkpfs import from SMB: ${filename} (${stat.size} bytes)`);
    res.json({ success: true, file: filename, size: stat.size });
  } catch (err) {
    log('error', `mkpfs import-from-smb failed: ${err.message}`);
    res.status(500).json({ error: err.message });
  }
});

const folderImportJobs = new Map();

router.post('/mkpfs/import-folder-from-smb', async (req, res) => {
  try {
    const { source_id, smb_path, folder_name, dest_name } = req.body;
    if (!source_id || !folder_name) return res.status(400).json({ error: 'source_id and folder_name required' });
    const src = getSource(parseInt(source_id));
    if (!src || src.type !== 'smb') return res.status(404).json({ error: 'SMB source not found' });

    ensureMkpfsDir();
    const cleanShare = (smb_path || src.path || '').replace(/\\/g, '/').replace(/^\/+/, '');
    const remoteDir = cleanShare ? `${cleanShare}/${folder_name}` : folder_name;
    const localDir = path.join(mkpfsWorkDir, (dest_name || folder_name).replace(/[^A-Za-z0-9_.\-]/g, '_'));
    if (!isInsideWorkDir(localDir)) return res.status(400).json({ error: 'Out of work dir' });
    if (!fs.existsSync(localDir)) fs.mkdirSync(localDir, { recursive: true });

    const jobId = newJobId();
    const job = {
      id: jobId,
      type: 'smb-folder-import',
      status: 'running',
      log: '',
      started_at: new Date().toISOString(),
      finished_at: null,
      remoteDir,
      localDir,
      error: null,
    };
    folderImportJobs.set(jobId, job);
    res.json({ success: true, job_id: jobId, dest: localDir });

    (async () => {
      const args = buildSmbArgs(src);
      args.push('-c', `prompt OFF; recurse ON; lcd "${localDir}"; cd "${remoteDir}"; mget *`);
      appendLog(job, `[smb] $ smbclient ${args.filter(a => a !== src.smb_password).join(' ')}\n`);
      const proc = spawn('smbclient', args);
      job._proc = proc;
      proc.stdout.on('data', d => appendLog(job, d));
      proc.stderr.on('data', d => appendLog(job, d));
      proc.on('error', err => {
        job.status = 'failed';
        job.error = err.message;
        job.finished_at = new Date().toISOString();
      });
      proc.on('close', code => {
        job.exit_code = code;
        job.finished_at = new Date().toISOString();
        if (code === 0) job.status = 'completed';
        else { job.status = 'failed'; job.error = `exit ${code}`; }
        log('info', `smb folder import ${jobId} ${job.status}`);
      });
    })().catch(err => {
      job.status = 'failed';
      job.error = err.message;
      job.finished_at = new Date().toISOString();
    });
  } catch (err) {
    log('error', `import-folder-from-smb failed: ${err.message}`);
    res.status(500).json({ error: err.message });
  }
});

router.get('/mkpfs/import-folder-from-smb/:id', (req, res) => {
  const job = folderImportJobs.get(req.params.id);
  if (!job) return res.status(404).json({ error: 'Job not found' });
  const { _proc, ...safe } = job;
  res.json(safe);
});

const extractJobs = new Map();

function detectArchiveType(name) {
  const n = name.toLowerCase();
  if (n.endsWith('.7z')) return '7z';
  if (n.endsWith('.rar') || /\.r\d{2}$/.test(n) || /\.part\d+\.rar$/.test(n)) return 'rar';
  if (n.endsWith('.zip')) return 'zip';
  if (n.endsWith('.tar.gz') || n.endsWith('.tgz')) return 'tgz';
  if (n.endsWith('.tar')) return 'tar';
  return null;
}

function getRarVolumes(filename) {
  const m1 = filename.match(/^(.*?)\.part(\d+)\.rar$/i);
  if (m1) {
    const base = m1[1];
    const padding = m1[2].length;
    return { base, pattern: 'partN', padding, ext: 'rar' };
  }
  const m2 = filename.match(/^(.*?)\.rar$/i);
  if (m2) return { base: m2[1], pattern: 'r00', ext: 'rar' };
  return null;
}

async function downloadSmbFiles(src, remoteDir, filenames, localDir, job) {
  for (const name of filenames) {
    const remote = remoteDir ? `${remoteDir}/${name}` : name;
    const local = path.join(localDir, name);
    appendLog(job, `[smb] get ${name}\n`);
    const args = buildSmbArgs(src);
    args.push('-c', `get "${remote}" "${local}"`);
    const { stdout, code } = await runSmbClient(args);
    const e = smbClientError(stdout, code);
    if (e) throw new Error(`Download ${name}: ${e.message}`);
  }
}

async function listSmbDir(src, remoteDir) {
  const args = buildSmbArgs(src);
  args.push('-c', remoteDir ? `cd "${remoteDir}"; ls` : 'ls');
  const { stdout, code } = await runSmbClient(args);
  const err = smbClientError(stdout, code);
  if (err) throw new Error(err.message);
  return parseSmbList(stdout);
}

function uploadDirToSmb(job, src, localDir, smbDir) {
  return smbUploadDir(src, localDir, smbDir, (text) => appendLog(job, text));
}

function validateExtractParams(body) {
  const {
    source = 'smb',
    source_id,
    smb_path = '',
    filename,
    local_path,
    dest_subdir,
    dest_kind: destKindRaw,
    dest_local_path,
  } = body || {};

  if (source !== 'smb' && source !== 'local' && source !== 'local-fs') {
    return { error: 'source must be smb, local, or local-fs' };
  }

  let archivePath;
  let smbSource = null;
  let smbRemoteDir = '';

  ensureMkpfsDir();

  if (source === 'smb') {
    if (!source_id || !filename) return { error: 'source_id and filename required' };
    smbSource = getSource(parseInt(source_id));
    if (!smbSource || smbSource.type !== 'smb') return { error: 'SMB source not found' };
    smbRemoteDir = (smb_path || '').replace(/\\/g, '/').replace(/^\/+/, '').replace(/\/+$/, '');
  } else if (source === 'local-fs') {
    if (!local_path) return { error: 'local_path required' };
    archivePath = path.resolve(local_path);
    if (!isLocalPathAllowed(archivePath)) return { error: 'Path not allowed' };
    if (!fs.existsSync(archivePath) || !fs.statSync(archivePath).isFile()) return { error: 'Archive not found' };
  } else {
    if (!local_path) return { error: 'local_path required' };
    archivePath = path.resolve(mkpfsWorkDir, local_path.replace(/\\/g, '/').replace(/^\/+/, ''));
    if (!isInsideWorkDir(archivePath)) return { error: 'Out of work dir' };
    if (!fs.existsSync(archivePath)) return { error: 'Archive not found' };
  }

  const archiveName = source === 'smb' ? filename : path.basename(archivePath);
  const archiveType = detectArchiveType(archiveName);
  if (!archiveType) return { error: `Unsupported archive type: ${archiveName}` };

  const stripExt = (n) => n.replace(/\.(7z|rar|zip|tar\.gz|tgz|tar|r\d{2}|part\d+\.rar)$/i, '');

  let destKind = destKindRaw;
  if (!destKind) {
    if (source === 'smb') destKind = 'smb-back';
    else if (source === 'local-fs') destKind = 'local-fs';
    else destKind = 'workdir';
  }

  let destLabel;
  let plannedDestBase = null;
  if (destKind === 'smb-back') {
    if (source !== 'smb') return { error: 'smb-back destination requires source=smb' };
    destLabel = `smb://${smbSource.smb_host}/${smbSource.smb_share}${smbRemoteDir ? '/' + smbRemoteDir : ''}`;
  } else if (destKind === 'local-fs') {
    const baseDir = dest_local_path
      ? path.resolve(dest_local_path)
      : (source === 'local-fs' ? path.dirname(archivePath) : mkpfsWorkDir);
    if (!isLocalPathAllowed(baseDir)) return { error: `Path not allowed: ${baseDir}` };
    plannedDestBase = path.join(baseDir, stripExt(archiveName));
    destLabel = plannedDestBase;
  } else {
    plannedDestBase = dest_subdir
      ? path.resolve(mkpfsWorkDir, dest_subdir.replace(/\\/g, '/').replace(/^\/+/, ''))
      : path.join(mkpfsWorkDir, stripExt(archiveName));
    if (!isInsideWorkDir(plannedDestBase)) return { error: 'destination out of work dir' };
    destLabel = plannedDestBase;
  }

  return { source, smbSource, smbRemoteDir, archivePath, archiveName, archiveType, destKind, destLabel, plannedDestBase };
}

function buildExtractJob(body, prep) {
  return {
    id: newJobId(),
    type: 'extract',
    source: prep.source,
    dest_kind: prep.destKind,
    archive: prep.archiveName,
    dest: prep.destLabel,
    archive_type: prep.archiveType,
    status: 'running',
    log: '',
    progress: 0,
    started_at: new Date().toISOString(),
    finished_at: null,
    exit_code: null,
    error: null,
    _params: body,
    _prep: prep,
  };
}

async function executeExtractJob(job) {
  const { source, smbSource, smbRemoteDir, archivePath: prepArchivePath, archiveName,
    archiveType, destKind, plannedDestBase } = job._prep;
  const { filename, password = '', delete_archive_after = false } = job._params || {};

  let workingArchive = prepArchivePath;
  let smbDownloadDir = null;
  let smbBackTmpDir = null;
  let destBase = plannedDestBase;
  let smbFiles = source === 'smb' ? [filename] : [];

  try {
    if (destKind === 'smb-back') {
      smbBackTmpDir = fs.mkdtempSync(path.join(getDiskTmpRoot(), 'mm-extract-out-'));
      destBase = smbBackTmpDir;
    } else {
      try { fs.mkdirSync(destBase, { recursive: true }); }
      catch (e) {
        job.status = 'failed';
        job.error = `Cannot create dest: ${e.message}`;
        job.finished_at = new Date().toISOString();
        appendLog(job, `[manager] ERROR: ${job.error}\n`);
        return;
      }
    }

    if (source === 'smb') {
      smbDownloadDir = fs.mkdtempSync(path.join(getDiskTmpRoot(), 'mm-extract-'));
      appendLog(job, `[manager] Listing remote dir ${smbRemoteDir || '/'} for related volumes...\n`);
      let remoteFiles = [];
      try {
        remoteFiles = await listSmbDir(smbSource, smbRemoteDir);
      } catch (e) {
        appendLog(job, `[manager] List failed: ${e.message} (continuing with single file)\n`);
      }

      if (archiveType === 'rar') {
        const vol = getRarVolumes(filename);
        if (vol) {
          if (vol.pattern === 'partN') {
            const re = new RegExp(`^${vol.base.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\.part(\\d+)\\.rar$`, 'i');
            smbFiles = remoteFiles.filter(f => !f.isDir && re.test(f.name)).map(f => f.name).sort();
          } else {
            const re = new RegExp(`^${vol.base.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\.(rar|r\\d{2,3})$`, 'i');
            smbFiles = remoteFiles.filter(f => !f.isDir && re.test(f.name)).map(f => f.name).sort();
            if (smbFiles.length === 0) smbFiles = [filename];
          }
        }
      } else if (archiveType === '7z') {
        const m = filename.match(/^(.*?)\.7z\.(\d+)$/i);
        if (m) {
          const base = m[1];
          const re = new RegExp(`^${base.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\.7z(\\.\\d+)?$`, 'i');
          smbFiles = remoteFiles.filter(f => !f.isDir && re.test(f.name)).map(f => f.name).sort();
        }
      }

      if (smbFiles.length === 0) smbFiles = [filename];
      appendLog(job, `[manager] Will download ${smbFiles.length} file(s): ${smbFiles.join(', ')}\n`);
      await downloadSmbFiles(smbSource, smbRemoteDir, smbFiles, smbDownloadDir, job);
      workingArchive = path.join(smbDownloadDir, filename);
    }

    appendLog(job, `[manager] Extracting ${path.basename(workingArchive)} (${archiveType}) → ${destBase}\n`);

    let cmd, args;
    if (archiveType === '7z' || archiveType === 'zip') {
      cmd = '7z';
      // -bsp1 emits "XX%" progress to stdout so the manager can show it in the queue
      args = ['x', workingArchive, `-o${destBase}`, '-y', '-bb1', '-bsp1'];
      if (password) args.splice(2, 0, `-p${password}`);
    } else if (archiveType === 'rar') {
      if (await hasBin('unrar')) {
        cmd = 'unrar';
        args = ['x', '-o+', '-y'];
        if (password) args.push(`-p${password}`); else args.push('-p-');
        args.push(workingArchive, destBase + '/');
      } else if (await hasBin('unar')) {
        cmd = 'unar';
        args = ['-o', destBase, '-f'];
        if (password) args.push('-p', password);
        args.push(workingArchive);
      } else {
        cmd = '7z';
        args = ['x', workingArchive, `-o${destBase}`, '-y'];
        if (password) args.splice(2, 0, `-p${password}`);
      }
    } else if (archiveType === 'tgz') {
      cmd = 'tar';
      args = ['-xzvf', workingArchive, '-C', destBase];
    } else if (archiveType === 'tar') {
      cmd = 'tar';
      args = ['-xvf', workingArchive, '-C', destBase];
    }

    const result = await spawnIntoJob(job, cmd, args);
    job.exit_code = result.code;
    job.finished_at = new Date().toISOString();

    if (result.code === 0) {
      if (destKind === 'smb-back') {
        appendLog(job, `[manager] Uploading extracted contents back to SMB...\n`);
        const upRes = await uploadDirToSmb(job, smbSource, destBase, smbRemoteDir);
        if (upRes.code !== 0) {
          job.status = 'failed';
          job.error = upRes.error || `smb upload exit ${upRes.code}`;
          return;
        }
        appendLog(job, `[manager] SMB upload OK\n`);
      }
      job.status = 'completed';
      appendLog(job, `[manager] Done.\n`);

      if (delete_archive_after) {
        if (source === 'local' && fs.existsSync(prepArchivePath)) {
          try { fs.unlinkSync(prepArchivePath); appendLog(job, `[manager] Deleted local archive: ${path.basename(prepArchivePath)}\n`); }
          catch (e) { appendLog(job, `[manager] Delete failed: ${e.message}\n`); }
        } else if (source === 'local-fs' && isLocalPathAllowed(prepArchivePath) && fs.existsSync(prepArchivePath)) {
          try { fs.unlinkSync(prepArchivePath); appendLog(job, `[manager] Deleted local archive: ${prepArchivePath}\n`); }
          catch (e) { appendLog(job, `[manager] Delete failed: ${e.message}\n`); }
        } else if (source === 'smb') {
          const delArgs = buildSmbArgs(smbSource);
          const cleanRemote = smbRemoteDir;
          const cmds = [];
          if (cleanRemote) cmds.push(`cd "${cleanRemote}"`);
          for (const f of smbFiles) cmds.push(`del "${f}"`);
          delArgs.push('-c', cmds.join('; '));
          appendLog(job, `[manager] Deleting ${smbFiles.length} SMB file(s): ${smbFiles.join(', ')}\n`);
          const { stdout, stderr, code } = await runSmbClient(delArgs);
          const out = stdout + stderr;
          const err = smbClientError(out, code);
          if (err) appendLog(job, `[manager] SMB delete warning: ${err.message}\n`);
          else appendLog(job, `[manager] SMB delete OK\n`);
        }
      }
    } else if (job.status !== 'cancelled') {
      job.status = 'failed';
      job.error = result.error || `exit ${result.code}`;
    }
  } catch (e) {
    job.status = 'failed';
    job.error = e.message;
    job.finished_at = new Date().toISOString();
    appendLog(job, `[manager] ERROR: ${e.message}\n`);
  } finally {
    if (smbDownloadDir) {
      try { fs.rmSync(smbDownloadDir, { recursive: true, force: true }); appendLog(job, `[manager] Cleaned up tmp\n`); }
      catch (_) {}
    }
    if (smbBackTmpDir) {
      try { fs.rmSync(smbBackTmpDir, { recursive: true, force: true }); appendLog(job, `[manager] Cleaned up extract tmp\n`); }
      catch (_) {}
    }
    log('info', `extract ${job.id} ${job.status}`);
  }
}

router.post('/extract', async (req, res) => {
  try {
    const prep = validateExtractParams(req.body);
    if (prep.error) return res.status(400).json({ error: prep.error });
    const job = buildExtractJob(req.body, prep);
    extractJobs.set(job.id, job);
    res.json({ success: true, job_id: job.id, dest: prep.destLabel, dest_kind: prep.destKind, archive_type: prep.archiveType });
    executeExtractJob(job).catch(e => {
      job.status = 'failed';
      job.error = e.message;
      job.finished_at = new Date().toISOString();
    });
  } catch (err) {
    log('error', `extract failed: ${err.message}`);
    res.status(500).json({ error: err.message });
  }
});

const extractQueue = [];
let extractQueuePaused = true;
let extractQueueWorkerRunning = false;

function extractQueueWorkerTick() {
  if (extractQueueWorkerRunning) return;
  if (extractQueuePaused) return;
  if (extractQueue.length === 0) return;
  const anyRunning = Array.from(extractJobs.values()).some(j => j.status === 'running');
  if (anyRunning) return;

  const next = extractQueue.find(q => q.status === 'queued');
  if (!next) return;

  extractQueueWorkerRunning = true;
  next.status = 'starting';

  try {
    const prep = validateExtractParams(next.params);
    if (prep.error) {
      next.status = 'failed';
      next.error = prep.error;
      next.finished_at = new Date().toISOString();
      extractQueueWorkerRunning = false;
      setTimeout(extractQueueWorkerTick, 50);
      return;
    }
    const job = buildExtractJob(next.params, prep);
    extractJobs.set(job.id, job);
    next.status = 'running';
    next.job_id = job.id;
    next.started_at = job.started_at;
    next.dest = prep.destLabel;
    next._job = job;

    executeExtractJob(job).then(() => {
      next.status = job.status;
      next.error = job.error || null;
      next.exit_code = job.exit_code;
      next.finished_at = job.finished_at;
      next.progress = job.progress;
    }).catch(err => {
      next.status = 'failed';
      next.error = err.message;
      next.finished_at = new Date().toISOString();
    }).finally(() => {
      extractQueueWorkerRunning = false;
      setTimeout(extractQueueWorkerTick, 100);
    });
  } catch (err) {
    next.status = 'failed';
    next.error = err.message;
    next.finished_at = new Date().toISOString();
    extractQueueWorkerRunning = false;
    setTimeout(extractQueueWorkerTick, 50);
  }
}

setInterval(extractQueueWorkerTick, 2000);

router.post('/extract/queue', (req, res) => {
  try {
    const params = req.body || {};
    const prep = validateExtractParams(params);
    if (prep.error) return res.status(400).json({ error: prep.error });
    const item = {
      id: newJobId(),
      params,
      source: prep.source,
      archive: prep.archiveName,
      archive_type: prep.archiveType,
      dest_kind: prep.destKind,
      dest: prep.destLabel,
      status: 'queued',
      added_at: new Date().toISOString(),
      started_at: null,
      finished_at: null,
      job_id: null,
      error: null,
      exit_code: null,
    };
    extractQueue.push(item);
    log('info', `mm extract-queue add ${item.id}: ${item.archive} → ${item.dest}`);
    setTimeout(extractQueueWorkerTick, 50);
    res.json({ success: true, item: { ...item, params: undefined } });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

function extractQueueItemPublic(item) {
  const { params, _job, ...rest } = item;
  if (_job && _job.progress != null) rest.progress = _job.progress;
  return rest;
}

router.get('/extract/queue', (req, res) => {
  res.json({
    paused: extractQueuePaused,
    items: extractQueue.map(extractQueueItemPublic),
  });
});

router.delete('/extract/queue/:id', (req, res) => {
  const id = req.params.id;
  const idx = extractQueue.findIndex(q => q.id === id);
  if (idx < 0) return res.status(404).json({ error: 'Item not found' });
  const item = extractQueue[idx];
  // cancel running task before removing it
  if (item.status === 'running' || item.status === 'starting') {
    const job = item._job || (item.job_id ? extractJobs.get(item.job_id) : null);
    if (job && job._proc) {
      try { job._proc.kill('SIGTERM'); } catch (_) {}
      job.status = 'cancelled';
      job.finished_at = new Date().toISOString();
    }
    item.status = 'cancelled';
    item.finished_at = new Date().toISOString();
    extractQueue.splice(idx, 1);
    return res.json({ success: true, cancelled: true });
  }
  if (item.status === 'queued' || ['completed', 'failed', 'cancelled'].includes(item.status)) {
    extractQueue.splice(idx, 1);
    return res.json({ success: true });
  }
  return res.status(400).json({ error: `Cannot remove item in status ${item.status}` });
});

router.post('/extract/queue/clear', (req, res) => {
  const before = extractQueue.length;
  for (let i = extractQueue.length - 1; i >= 0; i--) {
    if (extractQueue[i].status === 'queued') extractQueue.splice(i, 1);
  }
  res.json({ success: true, removed: before - extractQueue.length });
});

router.post('/extract/queue/clear-finished', (req, res) => {
  const before = extractQueue.length;
  for (let i = extractQueue.length - 1; i >= 0; i--) {
    if (['completed', 'failed', 'cancelled'].includes(extractQueue[i].status)) extractQueue.splice(i, 1);
  }
  res.json({ success: true, removed: before - extractQueue.length });
});

router.post('/extract/queue/pause', (req, res) => {
  extractQueuePaused = true;
  log('info', 'mm extract-queue paused');
  res.json({ success: true, paused: true });
});

router.post('/extract/queue/resume', (req, res) => {
  extractQueuePaused = false;
  log('info', 'mm extract-queue resumed');
  setTimeout(extractQueueWorkerTick, 50);
  res.json({ success: true, paused: false });
});

router.post('/extract/queue/:id/move', (req, res) => {
  const id = req.params.id;
  const dir = req.body?.direction;
  const idx = extractQueue.findIndex(q => q.id === id);
  if (idx < 0) return res.status(404).json({ error: 'Item not found' });
  if (extractQueue[idx].status !== 'queued') return res.status(400).json({ error: 'Only queued items can be moved' });
  if (dir === 'up' && idx > 0 && extractQueue[idx - 1].status === 'queued') {
    [extractQueue[idx - 1], extractQueue[idx]] = [extractQueue[idx], extractQueue[idx - 1]];
  } else if (dir === 'down' && idx < extractQueue.length - 1 && extractQueue[idx + 1].status === 'queued') {
    [extractQueue[idx], extractQueue[idx + 1]] = [extractQueue[idx + 1], extractQueue[idx]];
  }
  res.json({ success: true });
});

router.post('/extract/queue/:id/retry', (req, res) => {
  const id = req.params.id;
  const item = extractQueue.find(q => q.id === id);
  if (!item) return res.status(404).json({ error: 'Item not found' });
  if (!['failed', 'cancelled'].includes(item.status)) {
    return res.status(400).json({ error: `Cannot retry item in status ${item.status}` });
  }
  item.status = 'queued';
  item.error = null;
  item.exit_code = null;
  item.started_at = null;
  item.finished_at = null;
  item.job_id = null;
  setTimeout(extractQueueWorkerTick, 50);
  res.json({ success: true });
});

function hasBin(name) {
  return new Promise((resolve) => {
    const p = spawn('which', [name]);
    p.on('close', code => resolve(code === 0));
    p.on('error', () => resolve(false));
  });
}

router.get('/extract/:id', (req, res) => {
  const job = extractJobs.get(req.params.id);
  if (!job) return res.status(404).json({ error: 'Job not found' });
  const { _proc, ...safe } = job;
  res.json(safe);
});

router.get('/extract', (req, res) => {
  const list = Array.from(extractJobs.values())
    .map(({ _proc, log: jobLog, ...rest }) => ({ ...rest, log_size: jobLog.length }))
    .sort((a, b) => (b.started_at || '').localeCompare(a.started_at || ''))
    .slice(0, 20);
  res.json(list);
});

function spawnIntoJob(job, cmd, args, opts = {}) {
  return new Promise((resolve) => {
    appendLog(job, `\n[manager] $ ${cmd} ${args.join(' ')}\n`);
    const proc = spawn(cmd, args, opts);
    job._proc = proc;
    job.pid = proc.pid;
    proc.stdout.on('data', d => appendLog(job, d));
    proc.stderr.on('data', d => appendLog(job, d));
    proc.on('error', err => {
      appendLog(job, `[manager] error: ${err.message}\n`);
      resolve({ code: -1, error: err.message });
    });
    proc.on('close', code => resolve({ code }));
  });
}

async function runPushAfter(job) {
  if (!job.push_after || !job.push_ip) return;
  appendLog(job, `\n[manager] Pushing ${path.basename(job.output)} to ${job.push_ip}:${job.push_dest} via FTP...\n`);
  job.status = 'pushing';
  try {
    const ftp = loadFtp();
    await uploadFileResilient(job.push_ip, ftp, job.output, job.push_dest, path.basename(job.output), {
      onLog: (line) => appendLog(job, line),
      onProgress: ({ bytes, total }) => {
        if (total > 0) job.progress = Math.min(100, Math.round((bytes / total) * 100));
      },
    });
    appendLog(job, `[manager] Push OK\n`);
    job.status = 'completed';
  } catch (e) {
    appendLog(job, `[manager] Push failed: ${e.message}\n`);
    job.status = 'push_failed';
    job.error = e.message;
  }
}

function getDiskTmpRoot() {
  const tmpRoot = path.join(mkpfsWorkDir, '.tmp');
  try { fs.mkdirSync(tmpRoot, { recursive: true }); } catch (_) {}
  return tmpRoot;
}

function getMkpfsTmpDir(job) {
  const tmpRoot = getDiskTmpRoot();
  appendLog(job, `[manager] TMPDIR=${tmpRoot} (avoid filling /tmp tmpfs)\n`);
  return tmpRoot;
}

function mkpfsEnv(job) {
  const tmp = getMkpfsTmpDir(job);
  return {
    cwd: mkpfsWorkDir,
    env: { ...process.env, TMPDIR: tmp, TMP: tmp, TEMP: tmp },
  };
}

async function runPackFile(job, opts) {
  const args = ['pack', 'file'];
  args.push(opts.compress ? '--compress' : '--no-compress');
  if (opts.verify) args.push('--verify');
  if (opts.version) args.push('--version', opts.version);
  if (opts.block_size) args.push('--block-size', String(opts.block_size));
  if (opts.compression_level !== undefined && opts.compression_level !== null && opts.compression_level !== '') {
    args.push('--compression-level', String(opts.compression_level));
  }
  args.push('--verbose');
  args.push(job.source, job.output);
  job.command = `${MKPFS_BIN} ${args.join(' ')}`;
  return spawnIntoJob(job, MKPFS_BIN, args, mkpfsEnv(job));
}

async function runPackFolder(job, opts) {
  const args = ['pack', 'folder'];
  args.push(opts.compress ? '--compress' : '--no-compress');
  if (opts.verify) args.push('--verify');
  if (opts.version) args.push('--version', opts.version);
  if (opts.block_size) args.push('--block-size', String(opts.block_size));
  if (opts.compression_level !== undefined && opts.compression_level !== null && opts.compression_level !== '') {
    args.push('--compression-level', String(opts.compression_level));
  }
  if (opts.case_sensitive) args.push('--case-sensitive');
  if (opts.skip_executable_compression) args.push('--skip-executable-compression');
  if (opts.signed) args.push('--signed');
  if (opts.require_game_files) args.push('--require-game-files');
  args.push('--verbose');
  args.push(job.source, job.output);
  job.command = `${MKPFS_BIN} ${args.join(' ')}`;
  return spawnIntoJob(job, MKPFS_BIN, args, mkpfsEnv(job));
}

function validateConvertParams(params) {
  const {
    mode = 'pack-file',
    source_path,
  } = params;
  if (!source_path) return { error: 'source_path required' };
  if (!['pack-file', 'pack-folder'].includes(mode)) return { error: 'invalid mode' };
  ensureMkpfsDir();

  const isAbsolute = source_path.startsWith('/');
  let src;
  if (isAbsolute) {
    src = path.resolve(source_path);
    if (!isLocalPathAllowed(src)) return { error: `Path not allowed: ${src}` };
  } else {
    src = path.resolve(mkpfsWorkDir, source_path.replace(/\\/g, '/').replace(/^\/+/, ''));
    if (!isInsideWorkDir(src)) return { error: 'Source must be within work dir' };
  }
  if (!fs.existsSync(src)) return { error: 'Source not found' };
  const stat = fs.statSync(src);
  if (mode === 'pack-file' && !stat.isFile()) return { error: 'Source must be a file for pack-file mode' };
  if (mode === 'pack-folder' && !stat.isDirectory()) return { error: 'Source must be a directory for pack-folder mode' };
  const baseName = params.output_name && params.output_name.trim()
    ? params.output_name.trim()
    : path.basename(src).replace(/\.(exfat|ffpkg|ffpfsc)$/i, '') + '.ffpfsc';
  const out = path.join(path.dirname(src), baseName);
  return { src, stat, out, baseName };
}

function buildConvertJob(params, validated) {
  const jobId = newJobId();
  return {
    id: jobId,
    mode: params.mode || 'pack-file',
    status: 'running',
    command: '',
    source: validated.src,
    output: validated.out,
    log: '',
    progress: 0,
    started_at: new Date().toISOString(),
    finished_at: null,
    exit_code: null,
    error: null,
    pid: null,
    push_after: !!params.push_after,
    push_ip: params.push_ip || null,
    push_dest: params.push_dest || '/data/homebrew',
    delete_source_after: !!params.delete_source_after,
    _params: params,
  };
}

async function executeConvertJob(job) {
  const params = job._params || {};
  const opts = {
    compress: params.compress !== false,
    verify: params.verify !== false,
    version: params.version || 'PS5',
    block_size: params.block_size,
    compression_level: params.compression_level,
    case_sensitive: !!params.case_sensitive,
    skip_executable_compression: !!params.skip_executable_compression,
    signed: !!params.signed,
    require_game_files: !!params.require_game_files,
  };
  // Always overwrite existing output - mkpfs may refuse to write over existing .ffpfsc.
  if (job.output && fs.existsSync(job.output)) {
    try {
      fs.unlinkSync(job.output);
      appendLog(job, `[manager] Removed existing output ${path.basename(job.output)} (overwrite)\n`);
    } catch (e) {
      appendLog(job, `[manager] WARNING: could not remove existing output: ${e.message}\n`);
    }
  }
  let result;
  try {
    if (job.mode === 'pack-file') result = await runPackFile(job, opts);
    else if (job.mode === 'pack-folder') result = await runPackFolder(job, opts);
  } catch (e) {
    result = { code: -1, error: e.message };
  }

  job.exit_code = result.code;
  job.finished_at = new Date().toISOString();
  if (result.code === 0) {
    job.status = 'completed';
    log('info', `mm job ${job.id} completed (${job.mode}): ${path.basename(job.output)}`);

    if (job.delete_source_after && fs.existsSync(job.source)) {
      try {
        if (fs.statSync(job.source).isDirectory()) fs.rmSync(job.source, { recursive: true, force: true });
        else fs.unlinkSync(job.source);
        appendLog(job, `\n[manager] Deleted source ${path.basename(job.source)}\n`);
      } catch (e) {
        appendLog(job, `\n[manager] Failed to delete source: ${e.message}\n`);
      }
    }
    await runPushAfter(job);
  } else if (job.status === 'cancelled') {
    log('info', `mm job ${job.id} cancelled`);
  } else {
    job.status = 'failed';
    job.error = result.error || `exit ${result.code}`;
    log('error', `mm job ${job.id} failed (${job.mode}): exit ${result.code}`);
  }
}

router.post('/convert', async (req, res) => {
  try {
    const v = validateConvertParams(req.body);
    if (v.error) return res.status(v.error.includes('not found') ? 404 : 400).json(v);

    const job = buildConvertJob(req.body, v);
    jobs.set(job.id, job);
    res.json({ success: true, job_id: job.id, output: job.output, mode: job.mode });

    executeConvertJob(job).catch(err => {
      job.status = 'failed';
      job.error = err.message;
      job.finished_at = new Date().toISOString();
    });
  } catch (err) {
    log('error', `mm convert failed: ${err.message}`);
    res.status(500).json({ error: err.message });
  }
});

const convertQueue = [];
let queuePaused = true;
let queueWorkerRunning = false;

function queueWorkerTick() {
  if (queueWorkerRunning) return;
  if (queuePaused) return;
  if (convertQueue.length === 0) return;
  // only block on running CONVERT jobs — extract runs in a separate queue/worker in parallel
  const anyRunning = Array.from(jobs.values()).some(j => j.status === 'running' || j.status === 'pushing');
  if (anyRunning) return;

  const next = convertQueue.find(q => q.status === 'queued');
  if (!next) return;

  queueWorkerRunning = true;
  next.status = 'starting';

  try {
    const v = validateConvertParams(next.params);
    if (v.error) {
      next.status = 'failed';
      next.error = v.error;
      next.finished_at = new Date().toISOString();
      queueWorkerRunning = false;
      setTimeout(queueWorkerTick, 50);
      return;
    }
    const job = buildConvertJob(next.params, v);
    jobs.set(job.id, job);
    next.status = 'running';
    next.job_id = job.id;
    next.started_at = job.started_at;
    next.output = job.output;
    next._job = job;

    executeConvertJob(job).then(() => {
      next.status = job.status;
      next.error = job.error || null;
      next.exit_code = job.exit_code;
      next.finished_at = job.finished_at;
      next.progress = job.progress;
    }).catch(err => {
      next.status = 'failed';
      next.error = err.message;
      next.finished_at = new Date().toISOString();
    }).finally(() => {
      queueWorkerRunning = false;
      setTimeout(queueWorkerTick, 100);
    });
  } catch (err) {
    next.status = 'failed';
    next.error = err.message;
    next.finished_at = new Date().toISOString();
    queueWorkerRunning = false;
    setTimeout(queueWorkerTick, 50);
  }
}

setInterval(queueWorkerTick, 2000);

router.post('/convert/queue', (req, res) => {
  try {
    const params = req.body || {};
    const v = validateConvertParams(params);
    if (v.error) return res.status(400).json({ error: v.error });

    const item = {
      id: newJobId(),
      params,
      mode: params.mode || 'pack-file',
      source: v.src,
      output: v.out,
      output_name: path.basename(v.out),
      source_name: path.basename(v.src),
      status: 'queued',
      added_at: new Date().toISOString(),
      started_at: null,
      finished_at: null,
      job_id: null,
      error: null,
      exit_code: null,
    };
    convertQueue.push(item);
    log('info', `mm queue add ${item.id}: ${item.source_name} -> ${item.output_name}`);
    setTimeout(queueWorkerTick, 50);
    res.json({ success: true, item: { ...item, params: undefined } });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

function convertQueueItemPublic(item) {
  const { params, _job, ...rest } = item;
  if (_job && _job.progress != null) rest.progress = _job.progress;
  return rest;
}

router.get('/convert/queue', (req, res) => {
  res.json({
    paused: queuePaused,
    items: convertQueue.map(convertQueueItemPublic),
  });
});

router.delete('/convert/queue/:id', (req, res) => {
  const id = req.params.id;
  const idx = convertQueue.findIndex(q => q.id === id);
  if (idx < 0) return res.status(404).json({ error: 'Item not found' });
  const item = convertQueue[idx];
  if (item.status === 'running' || item.status === 'starting') {
    const job = item._job || (item.job_id ? jobs.get(item.job_id) : null);
    if (job && job._proc) {
      try { job._proc.kill('SIGTERM'); } catch (_) {}
      job.status = 'cancelled';
      job.finished_at = new Date().toISOString();
    }
    item.status = 'cancelled';
    item.finished_at = new Date().toISOString();
    convertQueue.splice(idx, 1);
    return res.json({ success: true, cancelled: true });
  }
  if (item.status === 'queued' || ['completed', 'failed', 'cancelled'].includes(item.status)) {
    convertQueue.splice(idx, 1);
    return res.json({ success: true });
  }
  return res.status(400).json({ error: `Cannot remove item in status ${item.status}` });
});

router.post('/convert/queue/clear', (req, res) => {
  const before = convertQueue.length;
  for (let i = convertQueue.length - 1; i >= 0; i--) {
    if (convertQueue[i].status === 'queued') convertQueue.splice(i, 1);
  }
  res.json({ success: true, removed: before - convertQueue.length });
});

router.post('/convert/queue/clear-finished', (req, res) => {
  const before = convertQueue.length;
  for (let i = convertQueue.length - 1; i >= 0; i--) {
    if (['completed', 'failed', 'cancelled'].includes(convertQueue[i].status)) convertQueue.splice(i, 1);
  }
  res.json({ success: true, removed: before - convertQueue.length });
});

router.post('/convert/queue/pause', (req, res) => {
  queuePaused = true;
  log('info', 'mm queue paused');
  res.json({ success: true, paused: true });
});

router.post('/convert/queue/resume', (req, res) => {
  queuePaused = false;
  log('info', 'mm queue resumed');
  setTimeout(queueWorkerTick, 50);
  res.json({ success: true, paused: false });
});

router.post('/convert/queue/:id/move', (req, res) => {
  const id = req.params.id;
  const dir = req.body?.direction;
  const idx = convertQueue.findIndex(q => q.id === id);
  if (idx < 0) return res.status(404).json({ error: 'Item not found' });
  if (convertQueue[idx].status !== 'queued') return res.status(400).json({ error: 'Only queued items can be moved' });
  if (dir === 'up' && idx > 0 && convertQueue[idx - 1].status === 'queued') {
    [convertQueue[idx - 1], convertQueue[idx]] = [convertQueue[idx], convertQueue[idx - 1]];
  } else if (dir === 'down' && idx < convertQueue.length - 1 && convertQueue[idx + 1].status === 'queued') {
    [convertQueue[idx], convertQueue[idx + 1]] = [convertQueue[idx + 1], convertQueue[idx]];
  }
  res.json({ success: true });
});

router.post('/convert/queue/:id/retry', (req, res) => {
  const id = req.params.id;
  const item = convertQueue.find(q => q.id === id);
  if (!item) return res.status(404).json({ error: 'Item not found' });
  if (!['failed', 'cancelled'].includes(item.status)) {
    return res.status(400).json({ error: `Cannot retry item in status ${item.status}` });
  }
  item.status = 'queued';
  item.error = null;
  item.exit_code = null;
  item.started_at = null;
  item.finished_at = null;
  item.job_id = null;
  setTimeout(queueWorkerTick, 50);
  res.json({ success: true });
});

router.get('/convert/:id', (req, res) => {
  const job = jobs.get(req.params.id);
  if (!job) return res.status(404).json({ error: 'Job not found' });
  const { _proc, ...safe } = job;
  res.json(safe);
});

router.post('/convert/:id/cancel', (req, res) => {
  const job = jobs.get(req.params.id);
  if (!job) return res.status(404).json({ error: 'Job not found' });
  if (job._proc && (job.status === 'running' || job.status === 'pushing')) {
    try { job._proc.kill('SIGTERM'); } catch (_) {}
    job.status = 'cancelled';
    job.finished_at = new Date().toISOString();
  }
  res.json({ success: true });
});

router.get('/convert', (req, res) => {
  const list = Array.from(jobs.values())
    .map(({ _proc, log: jobLog, ...rest }) => ({ ...rest, log_size: jobLog.length }))
    .sort((a, b) => (b.started_at || '').localeCompare(a.started_at || ''))
    .slice(0, 30);
  res.json(list);
});

const ftpUploadQueue = [];
let ftpUploadPaused = true;
let ftpUploadWorkerRunning = false;

function ftpUploadWorkerTick() {
  if (ftpUploadWorkerRunning) return;
  if (ftpUploadPaused) return;
  if (ftpUploadQueue.length === 0) return;
  const anyRunning = ftpUploadQueue.some(j => j.status === 'running');
  if (anyRunning) return;
  const next = ftpUploadQueue.find(q => q.status === 'queued');
  if (!next) return;
  ftpUploadWorkerRunning = true;
  next.status = 'running';
  next.started_at = new Date().toISOString();
  executeFtpUploadJob(next).catch(err => {
    next.status = 'failed';
    next.error = err.message;
    next.finished_at = new Date().toISOString();
  }).finally(() => {
    ftpUploadWorkerRunning = false;
    setTimeout(ftpUploadWorkerTick, 100);
  });
}

setInterval(ftpUploadWorkerTick, 2000);

const ftpUploadJobs = new Map();
const MAX_FTP_LOG_LINES = 1000;

function newFtpJobId() { return crypto.randomBytes(8).toString('hex'); }

function appendFtpJobLog(job, chunk) {
  const text = chunk.toString();
  job.log += text;
  const lines = job.log.split('\n');
  if (lines.length > MAX_FTP_LOG_LINES) job.log = lines.slice(-MAX_FTP_LOG_LINES).join('\n');
}

async function executeFtpUploadJob(job) {
  const { ip, local_path, dest_path } = job;
  const ftp = loadFtp();
  let total = 0;
  try {
    try { total = fs.statSync(local_path).size; } catch (_) {}
    job.bytes_total = total;
    job.bytes_transferred = 0;
    job.progress = 0;
    appendFtpJobLog(job, `[manager] Uploading ${path.basename(local_path)} to ${ip}:${dest_path}\n`);
    await uploadFileResilient(ip, ftp, local_path, dest_path, path.basename(local_path), {
      onLog: (line) => appendFtpJobLog(job, line),
      onProgress: ({ bytes, total: t }) => {
        job.bytes_transferred = bytes;
        if (t > 0) job.progress = Math.min(100, Math.round((bytes / t) * 100));
      },
    });
    job.progress = 100;
    job.status = 'completed';
    appendFtpJobLog(job, `[manager] Upload OK\n`);
    log('info', `ftp-upload ${job.id} completed: ${path.basename(local_path)} -> ${ip}:${dest_path}`);
  } catch (e) {
    job.status = 'failed';
    job.error = e.message;
    appendFtpJobLog(job, `[manager] ERROR: ${e.message}\n`);
    log('error', `ftp-upload ${job.id} failed: ${e.message}`);
  } finally {
    job.finished_at = new Date().toISOString();
  }
}

router.post('/ftp/upload/queue', async (req, res) => {
  try {
    const { ip, local_path } = req.body || {};
    if (!ip || !local_path) return res.status(400).json({ error: 'ip and local_path required' });
    const absPath = path.resolve(local_path);
    if (!isLocalPathAllowed(absPath)) return res.status(403).json({ error: 'Path not allowed' });
    if (!fs.existsSync(absPath) || !fs.statSync(absPath).isFile()) return res.status(400).json({ error: 'Source file not found' });

    const destPath = loadConfig().target_directory || '/data/homebrew';
    const item = {
      id: newFtpJobId(),
      ip,
      local_path: absPath,
      dest_path: destPath,
      file_name: path.basename(absPath),
      status: 'queued',
      added_at: new Date().toISOString(),
      started_at: null,
      finished_at: null,
      job_id: null,
      error: null,
    };
    ftpUploadQueue.push(item);
    log('info', `ftp-upload queue add: ${item.file_name} -> ${ip}:${destPath}`);
    setTimeout(ftpUploadWorkerTick, 50);
    res.json({ success: true, item });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

function ftpUploadItemPublic(item) {
  const { log: _l, ...rest } = item;
  return rest;
}

router.get('/ftp/upload/queue', (req, res) => {
  res.json({ paused: ftpUploadPaused, items: ftpUploadQueue.map(ftpUploadItemPublic) });
});

router.delete('/ftp/upload/queue/:id', (req, res) => {
  const idx = ftpUploadQueue.findIndex(q => q.id === req.params.id);
  if (idx < 0) return res.status(404).json({ error: 'Item not found' });
  const item = ftpUploadQueue[idx];
  // FTP uploads can't be killed mid-stream cleanly from basic-ftp; mark cancelled and remove.
  // The stream will error on the next chunk write and the job promise will resolve.
  if (item.status === 'running') {
    item.status = 'cancelled';
    item.error = 'cancelled';
    item.finished_at = new Date().toISOString();
  }
  ftpUploadQueue.splice(idx, 1);
  res.json({ success: true });
});

router.post('/ftp/upload/queue/clear', (req, res) => {
  const before = ftpUploadQueue.length;
  for (let i = ftpUploadQueue.length - 1; i >= 0; i--) {
    if (ftpUploadQueue[i].status === 'queued') ftpUploadQueue.splice(i, 1);
  }
  res.json({ success: true, removed: before - ftpUploadQueue.length });
});

router.post('/ftp/upload/queue/clear-finished', (req, res) => {
  const before = ftpUploadQueue.length;
  for (let i = ftpUploadQueue.length - 1; i >= 0; i--) {
    if (['completed', 'failed', 'cancelled'].includes(ftpUploadQueue[i].status)) ftpUploadQueue.splice(i, 1);
  }
  res.json({ success: true, removed: before - ftpUploadQueue.length });
});

router.post('/ftp/upload/queue/pause', (req, res) => {
  ftpUploadPaused = true;
  res.json({ success: true, paused: true });
});

router.post('/ftp/upload/queue/resume', (req, res) => {
  ftpUploadPaused = false;
  setTimeout(ftpUploadWorkerTick, 50);
  res.json({ success: true, paused: false });
});

router.get('/ftp/upload/:id', (req, res) => {
  const job = ftpUploadJobs.get(req.params.id);
  if (!job) return res.status(404).json({ error: 'Job not found' });
  res.json(job);
});

router.get('/queue/all', (req, res) => {
  const extractData = {
    paused: extractQueuePaused,
    items: extractQueue.map(item => ({ ...extractQueueItemPublic(item), type: 'extract' })),
  };
  const convertData = {
    paused: queuePaused,
    items: convertQueue.map(item => ({ ...convertQueueItemPublic(item), type: 'convert' })),
  };
  const uploadData = {
    paused: ftpUploadPaused,
    items: ftpUploadQueue.map(item => ({ ...ftpUploadItemPublic(item), type: 'upload' })),
  };

  const allItems = [
    ...extractData.items,
    ...convertData.items,
    ...uploadData.items,
  ].sort((a, b) => {
    const statusOrder = { running: 0, queued: 1, completed: 2, failed: 3, cancelled: 4 };
    const aOrder = statusOrder[a.status] ?? 5;
    const bOrder = statusOrder[b.status] ?? 5;
    if (aOrder !== bOrder) return aOrder - bOrder;
    return new Date(b.added_at || 0) - new Date(a.added_at || 0);
  });

  res.json({
    extract: extractData,
    convert: convertData,
    upload: uploadData,
    all: allItems,
    paused: {
      extract: extractQueuePaused,
      convert: queuePaused,
      upload: ftpUploadPaused,
    },
  });
});

router.post('/queue/pause-all', (req, res) => {
  extractQueuePaused = true;
  queuePaused = true;
  ftpUploadPaused = true;
  log('info', 'All queues paused');
  res.json({ success: true });
});

router.post('/queue/resume-all', (req, res) => {
  extractQueuePaused = false;
  queuePaused = false;
  ftpUploadPaused = false;
  log('info', 'All queues resumed');
  setTimeout(queueWorkerTick, 50);
  setTimeout(ftpUploadWorkerTick, 50);
  res.json({ success: true });
});

router.post('/queue/clear-finished', (req, res) => {
  let removed = 0;
  for (let i = extractQueue.length - 1; i >= 0; i--) {
    if (['completed', 'failed', 'cancelled'].includes(extractQueue[i].status)) {
      extractQueue.splice(i, 1);
      removed++;
    }
  }
  for (let i = convertQueue.length - 1; i >= 0; i--) {
    if (['completed', 'failed', 'cancelled'].includes(convertQueue[i].status)) {
      convertQueue.splice(i, 1);
      removed++;
    }
  }
  for (let i = ftpUploadQueue.length - 1; i >= 0; i--) {
    if (['completed', 'failed', 'cancelled'].includes(ftpUploadQueue[i].status)) {
      ftpUploadQueue.splice(i, 1);
      removed++;
    }
  }
  res.json({ success: true, removed });
});

export default router;
